version: '3.9'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=123
      - MYSQL_USER=root
      - MYSQL_DATABASE=todo
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306